---
- name: "Postgresql | Ensure PostgreSQL data directory exists"
  file:
    path: "{{ postgresql_data_dir }}/main"
    owner: postgres
    group: postgres
    state: directory
    mode: 0700

- name: "Postgresql | Check if Postgresql is initialized"
  stat:
    path: "{{ postgresql_data_dir }}/main/PG_VERSION"
  register: pgdata_dir_version

- name: "Postgresql | Initialize Postgresql"
  become_user: postgres
  command: "{{ postgresql_data_dir }}/bin/initdb -D {{ postgresql_data_dir }}/main"
  when: not pgdata_dir_version.stat.exists
